bootstrap.ts: fix TypeScript errors
resources/js/bootstrap.ts(2,8): error TS2339: Property 'axios' does not exist on type 'Window & typeof globalThis'.
resources/js/bootstrap.ts(4,8): error TS2339: Property 'axios' does not exist on type 'Window & typeof globalThis'.